//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PS.HireRocks.Data.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountType
    {
        public AccountType()
        {
            this.UserAccountTypes = new HashSet<UserAccountType>();
        }
    
        public long AccountTypeId { get; set; }
        public string AccountTypeName { get; set; }
    
        public virtual ICollection<UserAccountType> UserAccountTypes { get; set; }
    }
}
