//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PS.HireRocks.Data.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Capture
    {
        public long CaptureId { get; set; }
        public Nullable<int> KeyCount { get; set; }
        public Nullable<int> MouseCount { get; set; }
        public string KeyboardCapture { get; set; }
        public string MouseCapture { get; set; }
        public string ScreenCaptureThumbnailImage { get; set; }
        public string ScreenCaptureFullImage { get; set; }
        public Nullable<System.DateTime> CaptureDate { get; set; }
        public Nullable<decimal> TimeBurned { get; set; }
        public Nullable<long> ContractId { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> IsRejected { get; set; }
        public Nullable<long> MemoId { get; set; }
    
        public virtual Contract Contract { get; set; }
        public virtual Memo Memo { get; set; }
    }
}
