//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PS.HireRocks.Data.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Certification
    {
        public long CertificationId { get; set; }
        public string CertificationName { get; set; }
        public Nullable<System.DateTime> CertificationDate { get; set; }
        public string CertificationNumber { get; set; }
    }
}
