//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PS.HireRocks.Data.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public long CompanyId { get; set; }
        public string CompanyName { get; set; }
        public string CompanyOwner { get; set; }
        public string CompanyAddress { get; set; }
        public string Phone { get; set; }
        public string CompanyLogo { get; set; }
    }
}
