//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PS.HireRocks.Data.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractStatu
    {
        public ContractStatu()
        {
            this.Contracts = new HashSet<Contract>();
        }
    
        public long ContractStatusId { get; set; }
        public string ContractStatusName { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<Contract> Contracts { get; set; }
    }
}
