//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PS.HireRocks.Data.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contract
    {
        public Contract()
        {
            this.UserRatings = new HashSet<UserRating>();
            this.WorkerHourlyRates = new HashSet<WorkerHourlyRate>();
            this.UserPortfolios = new HashSet<UserPortfolio>();
            this.Captures = new HashSet<Capture>();
        }
    
        public long ContractId { get; set; }
        public Nullable<long> JobId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<decimal> EstimateDuration { get; set; }
        public Nullable<decimal> ActualDuration { get; set; }
        public Nullable<long> TimeUnitId { get; set; }
        public Nullable<long> ContractStatusId { get; set; }
        public Nullable<decimal> HoursLimit { get; set; }
        public string EndReason { get; set; }
        public Nullable<decimal> JobRating { get; set; }
        public string WorkerId { get; set; }
        public Nullable<decimal> FixedRate { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string CreatedByUserId { get; set; }
        public string ModifiedByUserId { get; set; }
        public Nullable<decimal> HourlyRate { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
        public virtual AspNetUser AspNetUser2 { get; set; }
        public virtual ICollection<UserRating> UserRatings { get; set; }
        public virtual ContractStatu ContractStatu { get; set; }
        public virtual ICollection<WorkerHourlyRate> WorkerHourlyRates { get; set; }
        public virtual Job Job { get; set; }
        public virtual TimeUnit TimeUnit { get; set; }
        public virtual ICollection<UserPortfolio> UserPortfolios { get; set; }
        public virtual ICollection<Capture> Captures { get; set; }
    }
}
