//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PS.HireRocks.Data.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class DegreeType
    {
        public DegreeType()
        {
            this.Educations = new HashSet<Education>();
        }
    
        public long DegreeTypeId { get; set; }
        public string DegreeTypeName { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<Education> Educations { get; set; }
    }
}
