//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PS.HireRocks.Data.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExperienceLevel
    {
        public ExperienceLevel()
        {
            this.Jobs = new HashSet<Job>();
        }
    
        public long ExperianceLevelId { get; set; }
        public string LevelName { get; set; }
        public bool IsActive { get; set; }
        public short ExperienceLowerRange { get; set; }
        public short ExperienceHigherRange { get; set; }
    
        public virtual ICollection<Job> Jobs { get; set; }
    }
}
