//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PS.HireRocks.Data.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        public Job()
        {
            this.Contracts = new HashSet<Contract>();
            this.JobAttachments = new HashSet<JobAttachment>();
            this.JobsBids = new HashSet<JobsBid>();
            this.Messages = new HashSet<Message>();
        }
    
        public long JobId { get; set; }
        public string JobTitle { get; set; }
        public string JobDescription { get; set; }
        public bool IsActive { get; set; }
        public bool IsHiringClosed { get; set; }
        public Nullable<long> WorkerTypeId { get; set; }
        public Nullable<long> ExperienceLevelExperianceLevelId { get; set; }
        public Nullable<long> JobTypeId { get; set; }
        public Nullable<long> JobSubCategoryId { get; set; }
        public string SkillsRequiredForJobIds { get; set; }
        public Nullable<System.DateTime> JobStartDate { get; set; }
        public Nullable<System.DateTime> JobEndDate { get; set; }
        public Nullable<decimal> EstimateDuration { get; set; }
        public Nullable<long> TimeUnitId { get; set; }
        public string ClientId { get; set; }
        public Nullable<System.DateTime> JobPostDate { get; set; }
        public Nullable<decimal> Min_PRF_Rate { get; set; }
        public Nullable<decimal> Max_PRF_Rate { get; set; }
        public string Locality_PRF { get; set; }
        public Nullable<decimal> FixedRate { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual ICollection<Contract> Contracts { get; set; }
        public virtual ExperienceLevel ExperienceLevel { get; set; }
        public virtual ICollection<JobAttachment> JobAttachments { get; set; }
        public virtual WorkerType WorkerType { get; set; }
        public virtual JobSubCategory JobSubCategory { get; set; }
        public virtual JobType JobType { get; set; }
        public virtual ICollection<JobsBid> JobsBids { get; set; }
        public virtual TimeUnit TimeUnit { get; set; }
        public virtual ICollection<Message> Messages { get; set; }
    }
}
