//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PS.HireRocks.Data.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobsBid
    {
        public JobsBid()
        {
            this.JobsBidAttachments = new HashSet<JobsBidAttachment>();
        }
    
        public long JobBidId { get; set; }
        public long JobId { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public string WorkerId { get; set; }
        public Nullable<bool> IsHired { get; set; }
        public Nullable<bool> IsDenied { get; set; }
        public string CoverLetter { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Job Job { get; set; }
        public virtual ICollection<JobsBidAttachment> JobsBidAttachments { get; set; }
    }
}
