//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PS.HireRocks.Data.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobSubCategory
    {
        public JobSubCategory()
        {
            this.Jobs = new HashSet<Job>();
        }
    
        public long JobSubCategoryId { get; set; }
        public string SubCategoryName { get; set; }
        public string SubCategoryDescription { get; set; }
        public bool IsActive { get; set; }
        public Nullable<long> JobCategoryId { get; set; }
    
        public virtual JobCategory JobCategory { get; set; }
        public virtual ICollection<Job> Jobs { get; set; }
    }
}
