//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PS.HireRocks.Data.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Memo
    {
        public Memo()
        {
            this.Captures = new HashSet<Capture>();
        }
    
        public long MemoId { get; set; }
        public string MemoText { get; set; }
        public string WorkerId { get; set; }
        public Nullable<System.DateTime> LastUsedDate { get; set; }
    
        public virtual ICollection<Capture> Captures { get; set; }
    }
}
