//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PS.HireRocks.Data.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public long NotificationId { get; set; }
        public string NotificationText { get; set; }
        public Nullable<bool> IsViewed { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public System.DateTime DateTime { get; set; }
        public string UserId { get; set; }
        public string NotificationType { get; set; }
        public Nullable<long> ObjectId { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
