//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PS.HireRocks.Data.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReadyMadeTool
    {
        public long ToolId { get; set; }
        public string ToolName { get; set; }
        public string ToolDescription { get; set; }
        public string DownloadURL { get; set; }
        public string ToolLogo { get; set; }
        public string ToolVersion { get; set; }
        public string ToolOwnerId { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
