//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PS.HireRocks.Data.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAccountType
    {
        public long Id { get; set; }
        public Nullable<long> UserAccountTypeId { get; set; }
        public string UserId { get; set; }
    
        public virtual AccountType AccountType { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
