//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PS.HireRocks.Data.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfile
    {
        public long UserProfileId { get; set; }
        public string ProfileTitle { get; set; }
        public string UserSkillIds { get; set; }
        public string UserLanguageIds { get; set; }
        public Nullable<decimal> UserHourlyRate { get; set; }
        public string EducationIds { get; set; }
        public string UserSubCategoryIds { get; set; }
        public Nullable<decimal> UserRating { get; set; }
        public string UserId { get; set; }
        public string TimeZone { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string IntroductionVideo { get; set; }
        public string CertificationIds { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
